const cockVarations = [
	"cock",
	"dick",
	"penis",
	"pinto",
	"sausage",
	"chode",
	"bbc",
	"peen",
	"verga",
	"willy",
	"anaconda",
	"balogna",
	"ding",
	"dong",
	"bone",
	"felipe",
	"p\\s*word",
	"phallic",
	"phallus",
	"dingle",
	"rola",
	"badonkadonk",
	"hot\\s*dog",
	"banana",
	"snake",
	"rofl",
	"cok",
	"coc",
	"wiener",
	"c\\s+o\\s+c\\s+k",
	"d\\s+o\\s+n\\s+g",
	"glizzy",
	"peepee",
	"wang",
	"schlong",
	"7.5",
	"p\\s*p",
	"p\\s*e\\s*e\\s*p\\s*e\\s*e",
	"third\\s*leg",
  "schmeat",
];

export default {
	token: "NzUwMTMxMzU2NzY3NjE3MDk1.X02ERA.SZXK2JZPlmrpcEIsWMSo4phRdzU",
	cock: {
		emoji: {
			headerName: "yep",
			message: ["🇨", "🇴", "🇰", "🍤"],
			default: "🍤",
		},
		log: {
			mainLogDir: "./src/log/count.log",
			statsDir: "./src/log/tmp/",
			logIntervalMillis: 6.9 * 60 * 60 * 1000 /* ( 6.9 hour )*/,
		},
		celebration: {
			interval: 100,
			message: "I have seen the world 'cock' $c times. 🍤",
		},
		dickRegex: new RegExp(
			cockVarations.reduce((prev, curr) => prev + curr + "|") + "cock"
		),
	},
};
